import { Report } from '../models/Report.js';
import { Log } from '../models/Log.js';

export async function getReports(req, res) {
  try {
    const { facilityId = 'nmdc-kirandul-cv101', limit = 50 } = req.query;
    const reports = await Report.find({ facilityId })
      .sort({ generatedAt: -1 })
      .limit(parseInt(limit, 10))
      .lean();
    res.json({ success: true, reports });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

export async function createReport(req, res) {
  try {
    const {
      facilityId = 'nmdc-kirandul-cv101',
      title,
      type,
      generatedBy,
      totalTonnage,
      overallRiskScore,
      snapshotData
    } = req.body;

    const reportId = `REP-${Date.now().toString().slice(-6)}`;
    const report = await Report.create({
      id: reportId,
      facilityId,
      title: title || 'NMDC Conveyor Compliance & Splice Audit',
      type: type || 'SHIFT_AUDIT',
      generatedBy: generatedBy || 'Shift Operator',
      generatedAt: new Date(),
      totalTonnage: totalTonnage || '428,500 Tons',
      overallRiskScore: overallRiskScore || 25.0,
      status: 'APPROVED',
      snapshotData: snapshotData || {}
    });

    // Record AUDIT log in MongoDB
    await Log.create({
      facilityId,
      level: 'INFO',
      category: 'AUDIT',
      source: 'Compliance Reports Generator',
      message: `[REPORT FILED] Report ${report.id} (${report.title}) generated by ${report.generatedBy}. Type: ${report.type}`,
      details: { reportId: report.id, type: report.type, generatedBy: report.generatedBy },
      user: report.generatedBy
    });

    res.status(201).json({ success: true, report });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

export async function getReportById(req, res) {
  try {
    const { id } = req.params;
    const report = await Report.findOne({ id }).lean();
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found.' });
    }
    res.json({ success: true, report });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}
